load("@rules_pkg//pkg:mappings.bzl", "pkg_attributes", "pkg_mkdirs")
load(":runtime_image.bzl", "runtime_image", "runtime_index", "runtime_layers")

exports_files(["python_runtimes.MODULE.bazel"])

pkg_mkdirs(
    name = "app_dir",
    attributes = pkg_attributes(gid = 65532, mode = "0755", uid = 65532),
    dirs = ["app"],
)

pkg_mkdirs(
    name = "certs_dir",
    attributes = pkg_attributes(mode = "0755"),
    dirs = ["etc/certs"],
)

runtime_layers(arch = "amd64")
runtime_layers(arch = "arm64")

runtime_image(python_version = "3.13", arch = "amd64")
runtime_image(python_version = "3.13", arch = "arm64")
runtime_image(python_version = "3.14", arch = "amd64")
runtime_image(python_version = "3.14", arch = "arm64")

runtime_index(python_version = "3.13")
runtime_index(python_version = "3.14")
