"""Save exact Astral runtime inputs; ordinary Bazel builds never resolve latest."""

import json
import pathlib
import re
import tempfile
import urllib.request


MINORS = ("3.13", "3.14")
LATEST = "https://raw.githubusercontent.com/astral-sh/python-build-standalone/latest-release/latest-release.json"
RELEASES = "https://github.com/astral-sh/python-build-standalone/releases/download"
OUTPUT = pathlib.Path(__file__).with_name("python_runtimes.MODULE.bazel")


def manifest(tag, checksums):
    if not isinstance(tag, str) or not re.fullmatch(r"[0-9]{8}", tag):
        raise ValueError("invalid Astral release tag")
    records = {}
    for line in checksums.splitlines():
        fields = line.rsplit(maxsplit=1)
        if not fields:
            continue
        match = re.fullmatch(
            r"cpython-((?:3\.13|3\.14)\.[0-9]+)\+"
            + tag + r"-x86_64-unknown-linux-gnu-(install_only(?:_stripped)?)\.tar\.gz",
            fields[-1],
        )
        if not match:
            continue
        if len(fields) != 2 or not re.fullmatch(r"[0-9a-f]{64}", fields[0]):
            raise ValueError(f"invalid SHA-256 record: {line}")
        version, flavor = match.groups()
        key = (version, flavor)
        record = (version, f"{RELEASES}/{tag}/{fields[1]}", fields[0])
        if key in records and records[key] != record:
            raise ValueError(f"conflicting artifact records for Python {version}")
        records[key] = record
    selected = []
    for minor in MINORS:
        candidates = [v for v, _ in records if v.startswith(minor + ".")]
        if not candidates:
            raise ValueError(f"missing stable x86_64 Python artifacts: {minor}")
        version = max(candidates, key=lambda v: tuple(map(int, v.split("."))))
        if (version, "install_only_stripped") not in records:
            raise ValueError(f"missing stripped artifact for Python {version}")
        selected.append(records[version, "install_only_stripped"])
    return selected


def render(runtimes):
    content = (
        "# Generated by update_python_manifest.py; do not edit.\n\n"
        'python = use_extension("@rules_python//python/extensions:python.bzl", "python")\n'
        'python.defaults(python_version = "3.13")\n'
        "python.override(minor_mapping = {\n"
    )
    for version, _, _ in runtimes:
        content += f'    "{version.rsplit(".", 1)[0]}": "{version}",\n'
    content += "})\n"
    for version, url, sha in runtimes:
        content += (
            "python.single_version_platform_override(\n"
            '    platform = "x86_64-unknown-linux-gnu",\n'
            f'    python_version = "{version}",\n'
            f'    sha256 = "{sha}",\n'
            '    strip_prefix = "python",\n'
            f"    urls = [{json.dumps(url)}],\n"
            ")\n"
        )
    for minor in MINORS:
        content += f'python.toolchain(python_version = "{minor}")\n'
    return content + (
        "use_repo(\n"
        "    python,\n"
        '    "pythons_hub",\n'
        '    cpython_3_13 = "python_3_13_x86_64-unknown-linux-gnu",\n'
        '    cpython_3_14 = "python_3_14_x86_64-unknown-linux-gnu",\n'
        ")\n"
    )


def refresh(tag, checksums, destination=OUTPUT):
    contents = render(manifest(tag, checksums))
    with tempfile.NamedTemporaryFile(mode="w", dir=destination.parent, delete=False) as temporary:
        staged = pathlib.Path(temporary.name)
        try:
            temporary.write(contents)
            temporary.flush()
            staged.chmod(0o644)
            staged.replace(destination)
        finally:
            staged.unlink(missing_ok=True)
    return contents


def download(url):
    with urllib.request.urlopen(url, timeout=60) as response:
        return response.read().decode("utf-8")


if __name__ == "__main__":
    tag = json.loads(download(LATEST))["tag"]
    contents = refresh(tag, download(f"{RELEASES}/{tag}/SHA256SUMS"))
    print(contents, end="")
